### ISSUE TITLE
TextArea rows param

### ISSUE THREAD

**Issue by just-kir** [curtis-allan/Shad4Fasthtml#46]
When I use textarea like this:

```
    Textarea(
        name='msg',
        placeholder="Type a message",
        rows=1,
    ),
```
the rows param does not behave correctly for me for arguments < 3. So, when I type 2 or 1, it always does rows=3. For higher values it works.

**Comment by curtis-allan** [comment]
@just-kir The Textarea has a pre-defined min-height tailwind class applied by default, you can override it by simply specifying a new min-h class.

Add cls='min-h-min' or similar and it should work.

**Comment by just-kir** [comment]
oh, thanks a lot!
