### ISSUE TITLE
Error on shad4fast setup

### ISSUE THREAD

**Issue by Daniel-GraphTx** [curtis-allan/Shad4Fasthtml#53]
Hey, thanks for the project it looks amazing. For me `shad4fast setup` fails with the error below. The weird thing is that the curl command works if I execute it directly.

Can I just work download the file myself and work with it or does it need to be transformed by shad4fast? Asking because shad4fast works for me if I use `tw_cdn=True`, but I can't get it to work with standalone tailwind. Neither with the shad4fast config file or trying to configure it myself.

(base) ~/code/shad4fast_test(:|✔) ♥ shad4fast setup
Traceback (most recent call last):
  File "/Users/daniel/miniforge3/bin/shad4fast", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/daniel/miniforge3/lib/python3.12/site-packages/shad4fast/cli.py", line 93, in main
    setup()
  File "/Users/daniel/miniforge3/lib/python3.12/site-packages/shad4fast/cli.py", line 49, in setup
    subprocess.run(["curl", "-sLO", globals_css_url], check=True)
  File "/Users/daniel/miniforge3/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['curl', '-sLO', 'https://raw.githubusercontent.com/curtis-allan/shadcn-fasthtml-framework/main/globals.css']' returned non-zero exit status 35.

**Comment by curtis-allan** [comment]
@Daniel-GraphTx Thanks for pointing this out, just pushed an update that should fix this. Can you let me know how it goes?

**Comment by Daniel-GraphTx** [comment]
Thanks for the quick response. It's really weird, I've updated to shad4fast 1.2.9. Still I often get the same error (with Python 3.12.6). I've retried a few times. Sometimes it works.

Weirdly the command `curl -sLO https://raw.githubusercontent.com/curtis-allan/Shad4Fasthtml/main/globals.css` always works.

Here is the error message again:
shad4fast setup
Traceback (most recent call last):
  File "/Users/daniel/miniforge3/bin/shad4fast", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/daniel/miniforge3/lib/python3.12/site-packages/shad4fast/cli.py", line 93, in main
    setup()
  File "/Users/daniel/miniforge3/lib/python3.12/site-packages/shad4fast/cli.py", line 51, in setup
    subprocess.run(["curl", "-sLO", tailwind_config_url], check=True)
  File "/Users/daniel/miniforge3/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['curl', '-sLO', 'https://raw.githubusercontent.com/curtis-allan/Shad4Fasthtml/main/tailwind.config.js']' returned non-zero exit status 35.

**Comment by curtis-allan** [comment]
Thanks for the heads up, will try and repro it my end when I get a sec and figure out what's happened

**Comment by Daniel-GraphTx** [comment]
Thank you, let me know if any additional info from my side could help.

Also not so urgent as it works with retrying.

**Comment by Daniel-GraphTx** [comment]
Seems like the issue is deeper, rather at curl and SSL lib level. Somehow IPv6 and TLS 1.3 don't work properly on my brand new Mac: https://discussions.apple.com/thread/255186837?sortBy=rank
